# Generated by Django 5.2.4 on 2025-07-27 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_owner_board_owner_id_alter_board_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='core.user'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='task',
            name='reviewer',
        ),
        migrations.AddField(
            model_name='task',
            name='assignee',
            field=models.ManyToManyField(blank=True, null=True, related_name='assigned_tasks', to='core.user'),
        ),
        migrations.AddField(
            model_name='task',
            name='reviewer',
            field=models.ManyToManyField(blank=True, null=True, related_name='reviewed_tasks', to='core.user'),
        ),
    ]
