# Generated by Django 5.2.4 on 2025-07-31 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_board_members_alter_board_member_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='members',
            new_name='member',
        ),
    ]
