# Generated by Django 5.2.4 on 2025-07-31 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_board_member_alter_board_owner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
