# Generated by Django 5.2.4 on 2025-07-31 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_board_member_board_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assignees',
            new_name='assignee',
        ),
    ]
