# Generated by Django 5.2.4 on 2025-07-31 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_assignees_task_assignee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assignee',
            new_name='assignees',
        ),
    ]
