# Generated by Django 5.2.4 on 2025-08-03 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('to-do', 'to-do'), ('in-progress', 'in-progress'), ('done', 'done'), ('review', 'review')], default='to_do', max_length=20),
        ),
    ]
