# Generated by Django 5.2.2 on 2025-08-07 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_task_priority_alter_task_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='task_high_priority_count',
            new_name='tasks_high_prio_count',
        ),
    ]
